package com.example.personalphysicaltracker.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class Activity(
    //Room autoGenerated unique IDs
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val type: ActivityType,
    val startTime: Long,
    var endTime: Long? = null,
    var duration: Long? = null,
    var steps: Long? = null
)
